name: Run the tests, build the image

on:
  push:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Build and push the image
        run: |
          docker login --username millemaliu --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/millemaliu/final:latest --file Dockerfile .  
          docker push ghcr.io/millemaliu/final:latest 
